import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import { HeroBanner } from "@/components/hero-banner";

const inter = Inter({
	variable: "--font-inter",
	subsets: ["vietnamese"],
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
	title: "Furniture App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.variable} antialiased`}>
				<div className="min-h-screen flex items-center justify-center">
					<div className="flex w-[1300px] h-[900px]">
						<div className="flex-1 flex items-center justify-center">{children}</div>
						<div className="flex-1 hidden lg:flex items-center justify-start">
							<HeroBanner />
						</div>
					</div>
				</div>
			</body>
		</html>
	);
}
