import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { FooterSection } from "@/components/footer-section";
import { TopHeaderSection } from "@/components/top-header-section";
import { HeaderSection } from "@/components/header-section";
const inter = Inter({
	variable: "--font-inter",
	subsets: ["vietnamese"],
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
	title: "Furniture App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.variable} antialiased`}>
				<>
					<TopHeaderSection />
					<HeaderSection />
					{children}
					<FooterSection />
				</>
			</body>
		</html>
	);
}
