import type { Metadata } from "next";
import { Inter, Monsieur_La_Doulaise } from "next/font/google";
import { FooterSection } from "@/components/section/footer-section";
import { TopHeaderSection } from "@/components/section/top-header-section";
import { HeaderSection } from "@/components/section/header-section";
import { Toaster } from "@/components/ui/sonner";
import "@/app/globals.css";
// import { Providers } from "@/app/(main-layout)/providers";

const inter = Inter({
	variable: "--font-inter",
	subsets: ["vietnamese"],
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
	display: "swap",
});

const monsieur = Monsieur_La_Doulaise({
	variable: "--font-mosieur",
	subsets: ["latin"],
	weight: ["400"],
	display: "swap",
});

export const metadata: Metadata = {
	title: "Hoang Ha App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.variable} ${monsieur.variable} antialiased`}>
				<>
					{/* <Providers> */}
						<TopHeaderSection />
						<HeaderSection />
						{children}
						<FooterSection />
						<Toaster />
					{/* </Providers> */}
				</>
			</body>
		</html>
	);
}
