import { Inter } from "next/font/google";
import type { Metadata } from "next";
import "@/app/globals.css";
import { Toaster } from "sonner";


const inter = Inter({
    variable: "--font-inter",
    subsets: ["vietnamese"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
    display: "swap",
});


export const metadata: Metadata = {
	title: "Hoang Ha App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.variable} antialiased`}>
				<>
					{children}
					<Toaster/>
				</>
			</body>
		</html>
	);
}
